-- Campus Nexus schema.

-- =========================================================
-- 1. USERS
-- Admin is a backend service identity and is not stored in users.
-- Normal users are represented by users.account_role = 'student'.
-- =========================================================

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    full_name TEXT NOT NULL,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,

    account_role TEXT NOT NULL DEFAULT 'student',
    -- account_role: student

    date_of_birth DATE,

    department TEXT,
    semester INTEGER,
    batch_year INTEGER,

    bio TEXT,
    profile_photo_url TEXT,

    profile_visibility TEXT NOT NULL DEFAULT 'public',
    -- profile_visibility: public, private

    notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,

    reputation_score REAL NOT NULL DEFAULT 0.0,
    safety_score REAL NOT NULL DEFAULT 1.0,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CHECK (account_role = 'student'),
    CHECK (profile_visibility IN ('public', 'private'))
);

CREATE TABLE IF NOT EXISTS auth_sessions (
    token TEXT PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 2. FRIENDSHIPS
-- =========================================================

CREATE TABLE IF NOT EXISTS friendships (
    friendship_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    requester_id INTEGER NOT NULL,
    receiver_id INTEGER NOT NULL,

    status TEXT NOT NULL DEFAULT 'pending',
    -- status: pending, accepted, rejected, cancelled

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (requester_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (receiver_id) REFERENCES users(user_id) ON DELETE CASCADE,

    CHECK (requester_id <> receiver_id),
    CHECK (status IN ('pending', 'accepted', 'rejected', 'cancelled')),
    UNIQUE (requester_id, receiver_id)
);


-- =========================================================
-- 3. BLOCKS
-- =========================================================

CREATE TABLE IF NOT EXISTS user_blocks (
    blocker_id INTEGER NOT NULL,
    blocked_id INTEGER NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (blocker_id, blocked_id),

    FOREIGN KEY (blocker_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (blocked_id) REFERENCES users(user_id) ON DELETE CASCADE,

    CHECK (blocker_id <> blocked_id)
);


-- =========================================================
-- 4. REPORTS
-- Can report users, posts, comments, messages, marketplace items, or clubs.
-- =========================================================

CREATE TABLE IF NOT EXISTS reports (
    report_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reporter_id INTEGER NOT NULL,

    target_type TEXT NOT NULL,
    target_id INTEGER NOT NULL,

    reason TEXT,
    description TEXT,

    status TEXT NOT NULL DEFAULT 'pending',
    -- status: pending, reviewing, resolved, rejected

    reviewed_by INTEGER,
    reviewed_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (reporter_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (reviewed_by) REFERENCES users(user_id) ON DELETE SET NULL,

    CHECK (target_type IN ('user', 'post', 'comment', 'message', 'marketplace_item', 'club')),
    CHECK (status IN ('pending', 'reviewing', 'resolved', 'rejected'))
);


-- =========================================================
-- 5. CLUBS
-- Only the backend admin service identity should create clubs at the application layer.
-- =========================================================

CREATE TABLE IF NOT EXISTS clubs (
    club_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name TEXT NOT NULL UNIQUE,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    logo_url TEXT,
    status TEXT NOT NULL DEFAULT 'Open',

    created_by_service TEXT,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 6. CLUB MEMBERS
-- Admin can add users to clubs and assign roles.
-- Permission flags are included now so RBAC can be enforced later.
-- =========================================================

CREATE TABLE IF NOT EXISTS club_members (
    club_member_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    club_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,

    role TEXT NOT NULL DEFAULT 'member',
    -- role: member, president, vice_president, chairman, vice_chairman, secretary, treasurer

    can_post BOOLEAN NOT NULL DEFAULT FALSE,
    can_publish_event BOOLEAN NOT NULL DEFAULT FALSE,
    can_create_announcement BOOLEAN NOT NULL DEFAULT FALSE,
    can_manage_members BOOLEAN NOT NULL DEFAULT FALSE,

    status TEXT NOT NULL DEFAULT 'active',
    -- status: active, removed, left

    added_by_service TEXT,

    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (club_id) REFERENCES clubs(club_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,

    UNIQUE (club_id, user_id),

    CHECK (role IN ('member', 'president', 'vice_president', 'chairman', 'vice_chairman', 'secretary', 'treasurer')),
    CHECK (status IN ('active', 'removed', 'left'))
);

CREATE TABLE IF NOT EXISTS club_followers (
    club_id INTEGER NOT NULL REFERENCES clubs(club_id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (club_id, user_id)
);


-- =========================================================
-- 7. POSTS
-- Legacy primary media remains on posts; all post media is stored in post_media.
-- Club posts, announcements, events, and reposts are all stored as posts.
-- =========================================================

CREATE TABLE IF NOT EXISTS posts (
    post_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    author_id INTEGER NOT NULL,
    club_id INTEGER,

    post_type TEXT NOT NULL DEFAULT 'normal',
    -- post_type: normal, repost, club_post, announcement, event

    content TEXT,

    media_url TEXT,
    media_type TEXT,
    -- media_type: image, video, document

    original_post_id INTEGER,
    -- used when post_type = 'repost'

    visibility TEXT NOT NULL DEFAULT 'public',
    -- visibility: public, friends, club, private

    -- Event-specific fields. These remain NULL for normal posts.
    event_title TEXT,
    event_start_time TIMESTAMPTZ,
    event_end_time TIMESTAMPTZ,
    event_location TEXT,
    registration_link TEXT,

    like_count INTEGER NOT NULL DEFAULT 0,
    comment_count INTEGER NOT NULL DEFAULT 0,
    share_count INTEGER NOT NULL DEFAULT 0,
    bookmark_count INTEGER NOT NULL DEFAULT 0,
    repost_count INTEGER NOT NULL DEFAULT 0,
    report_count INTEGER NOT NULL DEFAULT 0,

    engagement_score DOUBLE PRECISION NOT NULL DEFAULT 0.0,

    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (author_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (club_id) REFERENCES clubs(club_id) ON DELETE SET NULL,
    FOREIGN KEY (original_post_id) REFERENCES posts(post_id) ON DELETE SET NULL,

    CHECK (post_type IN ('normal', 'repost', 'club_post', 'announcement', 'event')),
    CHECK (visibility IN ('public', 'friends', 'club', 'private')),
    CHECK (media_type IS NULL OR media_type IN ('image', 'video', 'document'))
);

CREATE TABLE IF NOT EXISTS post_media (
    media_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INTEGER NOT NULL REFERENCES posts(post_id) ON DELETE CASCADE,
    media_url TEXT NOT NULL,
    media_type TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    CHECK (media_type IN ('image', 'video'))
);


-- =========================================================
-- 8. COMMENTS
-- =========================================================

CREATE TABLE IF NOT EXISTS comments (
    comment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    post_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,

    content TEXT NOT NULL,

    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (post_id) REFERENCES posts(post_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);


-- =========================================================
-- 9. POST LIKES
-- =========================================================

CREATE TABLE IF NOT EXISTS post_likes (
    post_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (post_id, user_id),

    FOREIGN KEY (post_id) REFERENCES posts(post_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);


-- =========================================================
-- 10. POST BOOKMARKS
-- User can bookmark posts.
-- =========================================================

CREATE TABLE IF NOT EXISTS post_bookmarks (
    post_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (post_id, user_id),

    FOREIGN KEY (post_id) REFERENCES posts(post_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);


-- =========================================================
-- 11. POST SHARES
-- Multiple shares by the same user are allowed.
-- =========================================================

CREATE TABLE IF NOT EXISTS post_shares (
    share_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    post_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (post_id) REFERENCES posts(post_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);


-- =========================================================
-- 12. MARKETPLACE
-- Simplified marketplace with one image per item.
-- =========================================================

CREATE TABLE IF NOT EXISTS marketplace_items (
    item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    seller_id INTEGER NOT NULL,

    title TEXT NOT NULL,
    description TEXT,
    category TEXT,

    price NUMERIC(12, 2),
    image_url TEXT,

    status TEXT NOT NULL DEFAULT 'available',
    -- status: available, sold, removed

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (seller_id) REFERENCES users(user_id) ON DELETE CASCADE,

    CHECK (status IN ('available', 'sold', 'removed'))
);


-- =========================================================
-- 13. CHAT THREADS
-- =========================================================

CREATE TABLE IF NOT EXISTS chat_threads (
    thread_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    thread_type TEXT NOT NULL DEFAULT 'direct',
    -- thread_type: direct, club, marketplace

    club_id INTEGER,
    marketplace_item_id INTEGER,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (club_id) REFERENCES clubs(club_id) ON DELETE SET NULL,
    FOREIGN KEY (marketplace_item_id) REFERENCES marketplace_items(item_id) ON DELETE SET NULL,

    CHECK (thread_type IN ('direct', 'club', 'marketplace'))
);


-- =========================================================
-- 14. CHAT PARTICIPANTS
-- =========================================================

CREATE TABLE IF NOT EXISTS chat_participants (
    thread_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,

    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_read_at TIMESTAMPTZ,

    PRIMARY KEY (thread_id, user_id),

    FOREIGN KEY (thread_id) REFERENCES chat_threads(thread_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);


-- =========================================================
-- 15. CHAT MESSAGES
-- =========================================================

CREATE TABLE IF NOT EXISTS chat_messages (
    message_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    thread_id INTEGER NOT NULL,
    sender_id INTEGER NOT NULL,

    content TEXT,

    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (thread_id) REFERENCES chat_threads(thread_id) ON DELETE CASCADE,
    FOREIGN KEY (sender_id) REFERENCES users(user_id) ON DELETE CASCADE
);


-- =========================================================
-- 16. GAMES
-- =========================================================

CREATE TABLE IF NOT EXISTS games (
    game_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name TEXT NOT NULL,
    description TEXT,

    start_date TIMESTAMPTZ,
    end_date TIMESTAMPTZ,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 17. USER POINTS
-- Used to calculate leaderboard.
-- =========================================================

CREATE TABLE IF NOT EXISTS user_points (
    point_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id INTEGER NOT NULL,
    game_id INTEGER,

    points INTEGER NOT NULL,
    reason TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE SET NULL
);


-- =========================================================
-- 18. NOTIFICATIONS
-- Check users.notifications_enabled before showing/sending notifications.
-- =========================================================

CREATE TABLE IF NOT EXISTS notifications (
    notification_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id INTEGER NOT NULL,
    actor_id INTEGER,

    type TEXT NOT NULL,

    target_type TEXT,
    target_id INTEGER,

    message TEXT,

    is_read BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (actor_id) REFERENCES users(user_id) ON DELETE SET NULL
);


-- =========================================================
-- 19. INTERACTION EVENTS
-- Historical event log for ranking and trust calculation.
-- =========================================================

CREATE TABLE IF NOT EXISTS interaction_events (
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    actor_id INTEGER NOT NULL,
    target_user_id INTEGER,

    target_type TEXT NOT NULL,
    target_id INTEGER NOT NULL,

    event_type TEXT NOT NULL,
    weight DOUBLE PRECISION NOT NULL DEFAULT 0.0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (actor_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (target_user_id) REFERENCES users(user_id) ON DELETE CASCADE,

    CHECK (target_type IN ('user', 'post', 'comment', 'club', 'marketplace_item', 'message')),
    CHECK (event_type IN (
        'profile_view',
        'friend_request',
        'friend_accept',
        'post_view',
        'post_like',
        'post_comment',
        'post_share',
        'post_bookmark',
        'message_sent',
        'club_join',
        'report_created',
        'report_confirmed'
    ))
);


-- =========================================================
-- 20. USER TRUST SCORES
-- Stores viewer-to-author trust for CampusRank-style ranking.
-- For less than 100 users, this can be recalculated periodically or on demand.
-- =========================================================

CREATE TABLE IF NOT EXISTS user_trust_scores (
    viewer_id INTEGER NOT NULL,
    target_user_id INTEGER NOT NULL,

    friendship_score DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    club_score DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    interaction_score DOUBLE PRECISION NOT NULL DEFAULT 0.0,

    final_trust_score DOUBLE PRECISION NOT NULL DEFAULT 0.0,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (viewer_id, target_user_id),

    FOREIGN KEY (viewer_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (target_user_id) REFERENCES users(user_id) ON DELETE CASCADE,

    CHECK (viewer_id <> target_user_id)
);


-- =========================================================
-- 21. ADMIN LOGS
-- Optional audit trail for important admin actions.
-- Useful for tracking club creation, member assignment, and role changes.
-- =========================================================

CREATE TABLE IF NOT EXISTS admin_logs (
    log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    admin_actor TEXT NOT NULL DEFAULT 'service-admin',

    action_type TEXT NOT NULL,
    -- action_type: create_club, add_club_member, remove_club_member, change_club_role, review_report

    target_type TEXT,
    target_id INTEGER,

    description TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CHECK (action_type IN (
        'create_club',
        'add_club_member',
        'remove_club_member',
        'change_club_role',
        'review_report'
    ))
);


-- =========================================================
-- 22. TRIGGERS FOR COUNTS
-- These keep post counts updated automatically.
-- =========================================================

CREATE OR REPLACE FUNCTION campus_nexus_touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION campus_nexus_increment_post_like_count()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE posts SET like_count = like_count + 1 WHERE post_id = NEW.post_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION campus_nexus_decrement_post_like_count()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE posts SET like_count = GREATEST(like_count - 1, 0) WHERE post_id = OLD.post_id;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION campus_nexus_increment_post_comment_count()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE posts SET comment_count = comment_count + 1 WHERE post_id = NEW.post_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION campus_nexus_increment_post_bookmark_count()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE posts SET bookmark_count = bookmark_count + 1 WHERE post_id = NEW.post_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION campus_nexus_decrement_post_bookmark_count()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE posts SET bookmark_count = GREATEST(bookmark_count - 1, 0) WHERE post_id = OLD.post_id;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION campus_nexus_increment_post_share_count()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE posts SET share_count = share_count + 1 WHERE post_id = NEW.post_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION campus_nexus_increment_repost_count()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.post_type = 'repost' AND NEW.original_post_id IS NOT NULL THEN
        UPDATE posts SET repost_count = repost_count + 1 WHERE post_id = NEW.original_post_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION campus_nexus_increment_report_count()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.target_type = 'post' THEN
        UPDATE posts SET report_count = report_count + 1 WHERE post_id = NEW.target_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_like_insert ON post_likes;
CREATE TRIGGER trg_like_insert AFTER INSERT ON post_likes
FOR EACH ROW EXECUTE FUNCTION campus_nexus_increment_post_like_count();

DROP TRIGGER IF EXISTS trg_like_delete ON post_likes;
CREATE TRIGGER trg_like_delete AFTER DELETE ON post_likes
FOR EACH ROW EXECUTE FUNCTION campus_nexus_decrement_post_like_count();

DROP TRIGGER IF EXISTS trg_comment_insert ON comments;
CREATE TRIGGER trg_comment_insert AFTER INSERT ON comments
FOR EACH ROW EXECUTE FUNCTION campus_nexus_increment_post_comment_count();

DROP TRIGGER IF EXISTS trg_bookmark_insert ON post_bookmarks;
CREATE TRIGGER trg_bookmark_insert AFTER INSERT ON post_bookmarks
FOR EACH ROW EXECUTE FUNCTION campus_nexus_increment_post_bookmark_count();

DROP TRIGGER IF EXISTS trg_bookmark_delete ON post_bookmarks;
CREATE TRIGGER trg_bookmark_delete AFTER DELETE ON post_bookmarks
FOR EACH ROW EXECUTE FUNCTION campus_nexus_decrement_post_bookmark_count();

DROP TRIGGER IF EXISTS trg_share_insert ON post_shares;
CREATE TRIGGER trg_share_insert AFTER INSERT ON post_shares
FOR EACH ROW EXECUTE FUNCTION campus_nexus_increment_post_share_count();

DROP TRIGGER IF EXISTS trg_repost_insert ON posts;
CREATE TRIGGER trg_repost_insert AFTER INSERT ON posts
FOR EACH ROW EXECUTE FUNCTION campus_nexus_increment_repost_count();

DROP TRIGGER IF EXISTS trg_report_post_insert ON reports;
CREATE TRIGGER trg_report_post_insert AFTER INSERT ON reports
FOR EACH ROW EXECUTE FUNCTION campus_nexus_increment_report_count();


-- =========================================================
-- 23. INDEXES
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_department_semester ON users(department, semester);

CREATE INDEX IF NOT EXISTS idx_friendships_requester ON friendships(requester_id);
CREATE INDEX IF NOT EXISTS idx_friendships_receiver ON friendships(receiver_id);
CREATE INDEX IF NOT EXISTS idx_friendships_status ON friendships(status);

CREATE INDEX IF NOT EXISTS idx_club_members_club ON club_members(club_id);
CREATE INDEX IF NOT EXISTS idx_club_members_user ON club_members(user_id);
CREATE INDEX IF NOT EXISTS idx_club_members_role ON club_members(role);

CREATE INDEX IF NOT EXISTS idx_posts_author ON posts(author_id);
CREATE INDEX IF NOT EXISTS idx_posts_club ON posts(club_id);
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON posts(created_at);
CREATE INDEX IF NOT EXISTS idx_posts_type ON posts(post_type);
CREATE INDEX IF NOT EXISTS idx_post_media_post ON post_media(post_id, sort_order);

CREATE INDEX IF NOT EXISTS idx_comments_post ON comments(post_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON notifications(user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_interaction_actor ON interaction_events(actor_id);
CREATE INDEX IF NOT EXISTS idx_interaction_target_user ON interaction_events(target_user_id);
CREATE INDEX IF NOT EXISTS idx_trust_viewer_score ON user_trust_scores(viewer_id, final_trust_score);

CREATE INDEX IF NOT EXISTS idx_marketplace_status ON marketplace_items(status);
CREATE INDEX IF NOT EXISTS idx_chat_messages_thread ON chat_messages(thread_id);
CREATE INDEX IF NOT EXISTS idx_reports_status ON reports(status);
