-- Campus Nexus schema.

-- =========================================================
-- 1. USERS
-- Admin is a backend service identity and is not stored in users.
-- Normal users are represented by users."accountRole" = 'student'.
-- =========================================================

CREATE TABLE IF NOT EXISTS users (
    "userId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "fullName" TEXT NOT NULL,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    "passwordHash" TEXT NOT NULL,

    "accountRole" TEXT NOT NULL DEFAULT 'student',
    -- "accountRole": student

    "dateOfBirth" DATE,

    department TEXT,
    semester INTEGER,
    "batchYear" INTEGER,

    bio TEXT,
    "profilePhotoUrl" TEXT,

    "profileVisibility" TEXT NOT NULL DEFAULT 'public',
    -- "profileVisibility": public, private

    "notificationsEnabled" BOOLEAN NOT NULL DEFAULT TRUE,

    "reputationScore" REAL NOT NULL DEFAULT 0.0,
    "safetyScore" REAL NOT NULL DEFAULT 1.0,

    "isActive" BOOLEAN NOT NULL DEFAULT TRUE,

    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CHECK (semester IS NULL OR semester BETWEEN 1 AND 4),
    CHECK (department IS NULL OR department IN ('CS', 'Mech', 'ECE', 'Electrical')),
    CHECK ("accountRole" = 'student'),
    CHECK ("profileVisibility" IN ('public', 'private'))
);

CREATE TABLE IF NOT EXISTS auth_sessions (
    token TEXT PRIMARY KEY,
    "userId" INTEGER NOT NULL REFERENCES users("userId") ON DELETE CASCADE,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 2. FRIENDSHIPS
-- =========================================================

CREATE TABLE IF NOT EXISTS friendships (
    "friendshipId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Canonical unordered pair: the lower user id is stored first.
    "requesterId" INTEGER NOT NULL,
    "receiverId" INTEGER NOT NULL,

    status TEXT NOT NULL DEFAULT 'pending',
    -- status: pending, accepted, rejected, cancelled

    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY ("requesterId") REFERENCES users("userId") ON DELETE CASCADE,
    FOREIGN KEY ("receiverId") REFERENCES users("userId") ON DELETE CASCADE,

    CHECK ("requesterId" < "receiverId"),
    CHECK (status IN ('pending', 'accepted', 'rejected', 'cancelled')),
    UNIQUE ("requesterId", "receiverId")
);


-- =========================================================
-- 3. BLOCKS
-- =========================================================

CREATE TABLE IF NOT EXISTS user_blocks (
    "blockerId" INTEGER NOT NULL,
    "blockedId" INTEGER NOT NULL,

    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY ("blockerId", "blockedId"),

    FOREIGN KEY ("blockerId") REFERENCES users("userId") ON DELETE CASCADE,
    FOREIGN KEY ("blockedId") REFERENCES users("userId") ON DELETE CASCADE,

    CHECK ("blockerId" <> "blockedId")
);


-- =========================================================
-- 4. REPORTS
-- Can report users, posts, comments, messages, marketplace items, or clubs.
-- =========================================================

CREATE TABLE IF NOT EXISTS reports (
    "reportId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "reporterId" INTEGER NOT NULL,

    "targetType" TEXT NOT NULL,
    "targetId" INTEGER NOT NULL,

    reason TEXT,
    description TEXT,

    status TEXT NOT NULL DEFAULT 'pending',
    -- status: pending, reviewing, resolved, rejected

    "reviewedBy" INTEGER,
    "reviewedAt" TIMESTAMPTZ,

    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY ("reporterId") REFERENCES users("userId") ON DELETE CASCADE,
    FOREIGN KEY ("reviewedBy") REFERENCES users("userId") ON DELETE SET NULL,

    CHECK ("targetType" IN ('user', 'post', 'comment', 'message', 'marketplace_item', 'club')),
    CHECK (status IN ('pending', 'reviewing', 'resolved', 'rejected'))
);


-- =========================================================
-- 5. CLUBS
-- Only the backend admin service identity should create clubs at the application layer.
-- =========================================================

CREATE TABLE IF NOT EXISTS clubs (
    "clubId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name TEXT NOT NULL UNIQUE,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    "logoUrl" TEXT,
    status TEXT NOT NULL DEFAULT 'Open',

    "createdByService" TEXT,

    "isActive" BOOLEAN NOT NULL DEFAULT TRUE,

    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 6. CLUB MEMBERS
-- Admin can add users to clubs and assign roles.
-- Permission flags are included now so RBAC can be enforced later.
-- =========================================================

CREATE TABLE IF NOT EXISTS club_members (
    "clubMemberId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "clubId" INTEGER NOT NULL,
    "userId" INTEGER NOT NULL,

    role TEXT NOT NULL DEFAULT 'member',
    -- role: member, president, vice_president, chairman, vice_chairman, secretary, treasurer

    "canPost" BOOLEAN NOT NULL DEFAULT FALSE,
    "canPublishEvent" BOOLEAN NOT NULL DEFAULT FALSE,
    "canCreateAnnouncement" BOOLEAN NOT NULL DEFAULT FALSE,
    "canManageMembers" BOOLEAN NOT NULL DEFAULT FALSE,

    status TEXT NOT NULL DEFAULT 'active',
    -- status: active, removed, left

    "addedByService" TEXT,

    "joinedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY ("clubId") REFERENCES clubs("clubId") ON DELETE CASCADE,
    FOREIGN KEY ("userId") REFERENCES users("userId") ON DELETE CASCADE,

    UNIQUE ("clubId", "userId"),

    CHECK (role IN ('member', 'president', 'vice_president', 'chairman', 'vice_chairman', 'secretary', 'treasurer')),
    CHECK (status IN ('active', 'removed', 'left'))
);

CREATE TABLE IF NOT EXISTS club_followers (
    "clubId" INTEGER NOT NULL REFERENCES clubs("clubId") ON DELETE CASCADE,
    "userId" INTEGER NOT NULL REFERENCES users("userId") ON DELETE CASCADE,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("clubId", "userId")
);


-- =========================================================
-- 7. POSTS
-- Legacy primary media remains on posts; all post media is stored in post_media.
-- Club posts, announcements, events, and reposts are all stored as posts.
-- =========================================================

CREATE TABLE IF NOT EXISTS posts (
    "postId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "authorId" INTEGER NOT NULL,
    "clubId" INTEGER,

    "postType" TEXT NOT NULL DEFAULT 'normal',
    -- "postType": normal, repost, club_post, announcement, event

    content TEXT,

    "mediaUrl" TEXT,
    "mediaType" TEXT,
    -- "mediaType": image, video, document

    "originalPostId" INTEGER,
    -- used when "postType" = 'repost'

    visibility TEXT NOT NULL DEFAULT 'public',
    -- visibility: public, friends, club, private

    -- Event-specific fields. These remain NULL for normal posts.
    "eventTitle" TEXT,
    "eventStartTime" TIMESTAMPTZ,
    "eventEndTime" TIMESTAMPTZ,
    "eventLocation" TEXT,
    "registrationLink" TEXT,

    "likeCount" INTEGER NOT NULL DEFAULT 0,
    "commentCount" INTEGER NOT NULL DEFAULT 0,
    "shareCount" INTEGER NOT NULL DEFAULT 0,
    "bookmarkCount" INTEGER NOT NULL DEFAULT 0,
    "repostCount" INTEGER NOT NULL DEFAULT 0,
    "reportCount" INTEGER NOT NULL DEFAULT 0,

    "engagementScore" DOUBLE PRECISION NOT NULL DEFAULT 0.0,

    "isDeleted" BOOLEAN NOT NULL DEFAULT FALSE,

    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY ("authorId") REFERENCES users("userId") ON DELETE CASCADE,
    FOREIGN KEY ("clubId") REFERENCES clubs("clubId") ON DELETE SET NULL,
    FOREIGN KEY ("originalPostId") REFERENCES posts("postId") ON DELETE SET NULL,

    CHECK ("postType" IN ('normal', 'repost', 'club_post', 'announcement', 'event')),
    CHECK (visibility IN ('public', 'friends', 'club', 'private')),
    CHECK ("mediaType" IS NULL OR "mediaType" IN ('image', 'video', 'document'))
);

CREATE TABLE IF NOT EXISTS post_media (
    "mediaId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "postId" INTEGER NOT NULL REFERENCES posts("postId") ON DELETE CASCADE,
    "mediaUrl" TEXT NOT NULL,
    "mediaType" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    CHECK ("mediaType" IN ('image', 'video'))
);


-- =========================================================
-- 8. COMMENTS
-- =========================================================

CREATE TABLE IF NOT EXISTS comments (
    "commentId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "postId" INTEGER NOT NULL,
    "userId" INTEGER NOT NULL,

    content TEXT NOT NULL,

    "isDeleted" BOOLEAN NOT NULL DEFAULT FALSE,

    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY ("postId") REFERENCES posts("postId") ON DELETE CASCADE,
    FOREIGN KEY ("userId") REFERENCES users("userId") ON DELETE CASCADE
);


-- =========================================================
-- 9. POST LIKES
-- =========================================================

CREATE TABLE IF NOT EXISTS post_likes (
    "postId" INTEGER NOT NULL,
    "userId" INTEGER NOT NULL,

    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY ("postId", "userId"),

    FOREIGN KEY ("postId") REFERENCES posts("postId") ON DELETE CASCADE,
    FOREIGN KEY ("userId") REFERENCES users("userId") ON DELETE CASCADE
);


-- =========================================================
-- 10. POST BOOKMARKS
-- User can bookmark posts.
-- =========================================================

CREATE TABLE IF NOT EXISTS post_bookmarks (
    "postId" INTEGER NOT NULL,
    "userId" INTEGER NOT NULL,

    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY ("postId", "userId"),

    FOREIGN KEY ("postId") REFERENCES posts("postId") ON DELETE CASCADE,
    FOREIGN KEY ("userId") REFERENCES users("userId") ON DELETE CASCADE
);


-- =========================================================
-- 11. POST SHARES
-- Multiple shares by the same user are allowed.
-- =========================================================

CREATE TABLE IF NOT EXISTS post_shares (
    "shareId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "postId" INTEGER NOT NULL,
    "userId" INTEGER NOT NULL,

    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY ("postId") REFERENCES posts("postId") ON DELETE CASCADE,
    FOREIGN KEY ("userId") REFERENCES users("userId") ON DELETE CASCADE
);


-- =========================================================
-- 12. MARKETPLACE
-- Simplified marketplace with one image per item.
-- =========================================================

CREATE TABLE IF NOT EXISTS marketplace_items (
    "itemId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "sellerId" INTEGER NOT NULL,

    title TEXT NOT NULL,
    description TEXT,
    category TEXT,

    price NUMERIC(12, 2),
    "imageUrl" TEXT,

    status TEXT NOT NULL DEFAULT 'available',
    -- status: available, sold, removed

    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY ("sellerId") REFERENCES users("userId") ON DELETE CASCADE,

    CHECK (status IN ('available', 'sold', 'removed'))
);


-- =========================================================
-- 13. CHAT THREADS
-- =========================================================

CREATE TABLE IF NOT EXISTS chat_threads (
    "threadId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "threadType" TEXT NOT NULL DEFAULT 'direct',
    -- "threadType": direct, club, marketplace

    "clubId" INTEGER,
    "marketplaceItemId" INTEGER,

    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY ("clubId") REFERENCES clubs("clubId") ON DELETE SET NULL,
    FOREIGN KEY ("marketplaceItemId") REFERENCES marketplace_items("itemId") ON DELETE SET NULL,

    CHECK ("threadType" IN ('direct', 'club', 'marketplace'))
);


-- =========================================================
-- 14. CHAT PARTICIPANTS
-- =========================================================

CREATE TABLE IF NOT EXISTS chat_participants (
    "threadId" INTEGER NOT NULL,
    "userId" INTEGER NOT NULL,

    "joinedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastReadAt" TIMESTAMPTZ,

    PRIMARY KEY ("threadId", "userId"),

    FOREIGN KEY ("threadId") REFERENCES chat_threads("threadId") ON DELETE CASCADE,
    FOREIGN KEY ("userId") REFERENCES users("userId") ON DELETE CASCADE
);


-- =========================================================
-- 15. CHAT MESSAGES
-- =========================================================

CREATE TABLE IF NOT EXISTS chat_messages (
    "messageId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "threadId" INTEGER NOT NULL,
    "senderId" INTEGER NOT NULL,

    content TEXT,

    "isDeleted" BOOLEAN NOT NULL DEFAULT FALSE,

    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY ("threadId") REFERENCES chat_threads("threadId") ON DELETE CASCADE,
    FOREIGN KEY ("senderId") REFERENCES users("userId") ON DELETE CASCADE
);


-- =========================================================
-- 16. GAMES
-- =========================================================

CREATE TABLE IF NOT EXISTS games (
    "gameId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name TEXT NOT NULL,
    description TEXT,

    "startDate" TIMESTAMPTZ,
    "endDate" TIMESTAMPTZ,

    "isActive" BOOLEAN NOT NULL DEFAULT TRUE,

    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 17. USER POINTS
-- Used to calculate leaderboard.
-- =========================================================

CREATE TABLE IF NOT EXISTS user_points (
    "pointId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "userId" INTEGER NOT NULL,
    "gameId" INTEGER,

    points INTEGER NOT NULL,
    reason TEXT,

    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY ("userId") REFERENCES users("userId") ON DELETE CASCADE,
    FOREIGN KEY ("gameId") REFERENCES games("gameId") ON DELETE SET NULL
);


-- =========================================================
-- 18. NOTIFICATIONS
-- Check users."notificationsEnabled" before showing/sending notifications.
-- =========================================================

CREATE TABLE IF NOT EXISTS notifications (
    "notificationId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "userId" INTEGER NOT NULL,
    "actorId" INTEGER,

    type TEXT NOT NULL,

    "targetType" TEXT,
    "targetId" INTEGER,

    message TEXT,

    "isRead" BOOLEAN NOT NULL DEFAULT FALSE,

    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY ("userId") REFERENCES users("userId") ON DELETE CASCADE,
    FOREIGN KEY ("actorId") REFERENCES users("userId") ON DELETE SET NULL
);


-- =========================================================
-- 19. INTERACTION EVENTS
-- Historical event log for ranking and trust calculation.
-- =========================================================

CREATE TABLE IF NOT EXISTS interaction_events (
    "eventId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "actorId" INTEGER NOT NULL,
    "targetUserId" INTEGER,

    "targetType" TEXT NOT NULL,
    "targetId" INTEGER NOT NULL,

    "eventType" TEXT NOT NULL,
    weight DOUBLE PRECISION NOT NULL DEFAULT 0.0,

    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY ("actorId") REFERENCES users("userId") ON DELETE CASCADE,
    FOREIGN KEY ("targetUserId") REFERENCES users("userId") ON DELETE CASCADE,

    CHECK ("targetType" IN ('user', 'post', 'comment', 'club', 'marketplace_item', 'message')),
    CHECK ("eventType" IN (
        'profile_view',
        'friend_request',
        'friend_accept',
        'post_view',
        'post_like',
        'post_comment',
        'post_share',
        'post_bookmark',
        'message_sent',
        'club_join',
        'report_created',
        'report_confirmed'
    ))
);


-- =========================================================
-- 20. USER TRUST SCORES
-- Stores viewer-to-author trust for CampusRank-style ranking.
-- For less than 100 users, this can be recalculated periodically or on demand.
-- =========================================================

CREATE TABLE IF NOT EXISTS user_trust_scores (
    "viewerId" INTEGER NOT NULL,
    "targetUserId" INTEGER NOT NULL,

    "friendshipScore" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "clubScore" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "interactionScore" DOUBLE PRECISION NOT NULL DEFAULT 0.0,

    "finalTrustScore" DOUBLE PRECISION NOT NULL DEFAULT 0.0,

    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY ("viewerId", "targetUserId"),

    FOREIGN KEY ("viewerId") REFERENCES users("userId") ON DELETE CASCADE,
    FOREIGN KEY ("targetUserId") REFERENCES users("userId") ON DELETE CASCADE,

    CHECK ("viewerId" <> "targetUserId")
);


-- =========================================================
-- 21. ADMIN LOGS
-- Optional audit trail for important admin actions.
-- Useful for tracking club creation, member assignment, and role changes.
-- =========================================================

CREATE TABLE IF NOT EXISTS admin_logs (
    "logId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "adminActor" TEXT NOT NULL DEFAULT 'service-admin',

    "actionType" TEXT NOT NULL,
    -- "actionType": create_club, add_club_member, remove_club_member, change_club_role, review_report

    "targetType" TEXT,
    "targetId" INTEGER,

    description TEXT,

    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CHECK ("actionType" IN (
        'create_club',
        'add_club_member',
        'remove_club_member',
        'change_club_role',
        'review_report'
    ))
);


-- =========================================================
-- 22. TRIGGERS FOR COUNTS
-- These keep post counts updated automatically.
-- =========================================================

CREATE OR REPLACE FUNCTION campus_nexus_touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW."updatedAt" = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION campus_nexus_increment_post_like_count()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE posts SET "likeCount" = "likeCount" + 1 WHERE "postId" = NEW."postId";
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION campus_nexus_decrement_post_like_count()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE posts SET "likeCount" = GREATEST("likeCount" - 1, 0) WHERE "postId" = OLD."postId";
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION campus_nexus_increment_post_comment_count()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE posts SET "commentCount" = "commentCount" + 1 WHERE "postId" = NEW."postId";
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION campus_nexus_increment_post_bookmark_count()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE posts SET "bookmarkCount" = "bookmarkCount" + 1 WHERE "postId" = NEW."postId";
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION campus_nexus_decrement_post_bookmark_count()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE posts SET "bookmarkCount" = GREATEST("bookmarkCount" - 1, 0) WHERE "postId" = OLD."postId";
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION campus_nexus_increment_post_share_count()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE posts SET "shareCount" = "shareCount" + 1 WHERE "postId" = NEW."postId";
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION campus_nexus_increment_repost_count()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW."postType" = 'repost' AND NEW."originalPostId" IS NOT NULL THEN
        UPDATE posts SET "repostCount" = "repostCount" + 1 WHERE "postId" = NEW."originalPostId";
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION campus_nexus_increment_report_count()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW."targetType" = 'post' THEN
        UPDATE posts SET "reportCount" = "reportCount" + 1 WHERE "postId" = NEW."targetId";
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_like_insert ON post_likes;
CREATE TRIGGER trg_like_insert AFTER INSERT ON post_likes
FOR EACH ROW EXECUTE FUNCTION campus_nexus_increment_post_like_count();

DROP TRIGGER IF EXISTS trg_like_delete ON post_likes;
CREATE TRIGGER trg_like_delete AFTER DELETE ON post_likes
FOR EACH ROW EXECUTE FUNCTION campus_nexus_decrement_post_like_count();

DROP TRIGGER IF EXISTS trg_comment_insert ON comments;
CREATE TRIGGER trg_comment_insert AFTER INSERT ON comments
FOR EACH ROW EXECUTE FUNCTION campus_nexus_increment_post_comment_count();

DROP TRIGGER IF EXISTS trg_bookmark_insert ON post_bookmarks;
CREATE TRIGGER trg_bookmark_insert AFTER INSERT ON post_bookmarks
FOR EACH ROW EXECUTE FUNCTION campus_nexus_increment_post_bookmark_count();

DROP TRIGGER IF EXISTS trg_bookmark_delete ON post_bookmarks;
CREATE TRIGGER trg_bookmark_delete AFTER DELETE ON post_bookmarks
FOR EACH ROW EXECUTE FUNCTION campus_nexus_decrement_post_bookmark_count();

DROP TRIGGER IF EXISTS trg_share_insert ON post_shares;
CREATE TRIGGER trg_share_insert AFTER INSERT ON post_shares
FOR EACH ROW EXECUTE FUNCTION campus_nexus_increment_post_share_count();

DROP TRIGGER IF EXISTS trg_repost_insert ON posts;
CREATE TRIGGER trg_repost_insert AFTER INSERT ON posts
FOR EACH ROW EXECUTE FUNCTION campus_nexus_increment_repost_count();

DROP TRIGGER IF EXISTS trg_report_post_insert ON reports;
CREATE TRIGGER trg_report_post_insert AFTER INSERT ON reports
FOR EACH ROW EXECUTE FUNCTION campus_nexus_increment_report_count();


-- =========================================================
-- 23. INDEXES
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_department_semester ON users(department, semester);

CREATE INDEX IF NOT EXISTS idx_friendships_requester ON friendships("requesterId");
CREATE INDEX IF NOT EXISTS idx_friendships_receiver ON friendships("receiverId");
CREATE INDEX IF NOT EXISTS idx_friendships_status ON friendships(status);

CREATE INDEX IF NOT EXISTS idx_club_members_club ON club_members("clubId");
CREATE INDEX IF NOT EXISTS idx_club_members_user ON club_members("userId");
CREATE INDEX IF NOT EXISTS idx_club_members_role ON club_members(role);

CREATE INDEX IF NOT EXISTS idx_posts_author ON posts("authorId");
CREATE INDEX IF NOT EXISTS idx_posts_club ON posts("clubId");
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON posts("createdAt");
CREATE INDEX IF NOT EXISTS idx_posts_type ON posts("postType");
CREATE INDEX IF NOT EXISTS idx_post_media_post ON post_media("postId", "sortOrder");

CREATE INDEX IF NOT EXISTS idx_comments_post ON comments("postId");
CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON notifications("userId", "isRead");
CREATE INDEX IF NOT EXISTS idx_interaction_actor ON interaction_events("actorId");
CREATE INDEX IF NOT EXISTS idx_interaction_target_user ON interaction_events("targetUserId");
CREATE INDEX IF NOT EXISTS idx_trust_viewer_score ON user_trust_scores("viewerId", "finalTrustScore");

CREATE INDEX IF NOT EXISTS idx_marketplace_status ON marketplace_items(status);
CREATE INDEX IF NOT EXISTS idx_chat_messages_thread ON chat_messages("threadId");
CREATE INDEX IF NOT EXISTS idx_reports_status ON reports(status);
