-- Campus Nexus authoritative PostgreSQL schema
-- Generated from the verified production-equivalent schema on 2026-08-27.
-- Contains structure only; no users, credentials, or application data.

BEGIN;

--
-- PostgreSQL database dump
--



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: badges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.badges (
    "badgeId" character varying(80) NOT NULL,
    name character varying(120) NOT NULL,
    icon character varying(80) NOT NULL,
    description text,
    "isActive" boolean DEFAULT true NOT NULL,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: campus_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.campus_events (
    "eventId" integer NOT NULL,
    title character varying(160) NOT NULL,
    link character varying(2048) NOT NULL,
    "eventType" character varying(32) NOT NULL,
    "eventDate" date NOT NULL,
    place character varying(200) NOT NULL,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_campus_events_type CHECK ((("eventType")::text = ANY ((ARRAY['Competition'::character varying, 'Workshop'::character varying, 'Alumni Talk'::character varying])::text[])))
);


--
-- Name: campus_events_eventId_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.campus_events ALTER COLUMN "eventId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."campus_events_eventId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_messages (
    "messageId" integer CONSTRAINT chat_messages_message_id_not_null NOT NULL,
    "threadId" integer CONSTRAINT chat_messages_thread_id_not_null NOT NULL,
    "senderId" integer CONSTRAINT chat_messages_sender_id_not_null NOT NULL,
    content text,
    "isDeleted" boolean CONSTRAINT chat_messages_is_deleted_not_null NOT NULL,
    "createdAt" timestamp without time zone CONSTRAINT chat_messages_created_at_not_null NOT NULL
);


--
-- Name: chat_messages_message_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.chat_messages_message_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: chat_messages_message_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.chat_messages_message_id_seq OWNED BY public.chat_messages."messageId";


--
-- Name: chat_participants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_participants (
    "threadId" integer CONSTRAINT chat_participants_thread_id_not_null NOT NULL,
    "userId" integer CONSTRAINT chat_participants_user_id_not_null NOT NULL,
    "joinedAt" timestamp without time zone CONSTRAINT chat_participants_joined_at_not_null NOT NULL,
    "lastReadAt" timestamp without time zone
);


--
-- Name: chat_threads; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_threads (
    "threadId" integer CONSTRAINT chat_threads_thread_id_not_null NOT NULL,
    "threadType" text CONSTRAINT chat_threads_thread_type_not_null NOT NULL,
    "clubId" integer,
    "marketplaceItemId" integer,
    "createdAt" timestamp without time zone CONSTRAINT chat_threads_created_at_not_null NOT NULL,
    "directKey" character varying(64)
);


--
-- Name: chat_threads_thread_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.chat_threads_thread_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: chat_threads_thread_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.chat_threads_thread_id_seq OWNED BY public.chat_threads."threadId";


--
-- Name: club_followers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.club_followers (
    "clubId" integer CONSTRAINT club_followers_club_id_not_null NOT NULL,
    "userId" integer CONSTRAINT club_followers_user_id_not_null NOT NULL,
    "createdAt" timestamp without time zone CONSTRAINT club_followers_created_at_not_null NOT NULL
);


--
-- Name: club_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.club_members (
    "clubMemberId" integer CONSTRAINT club_members_club_member_id_not_null NOT NULL,
    "clubId" integer CONSTRAINT club_members_club_id_not_null NOT NULL,
    "userId" integer CONSTRAINT club_members_user_id_not_null NOT NULL,
    role text NOT NULL,
    "canPost" boolean CONSTRAINT club_members_can_post_not_null NOT NULL,
    "canPublishEvent" boolean CONSTRAINT club_members_can_publish_event_not_null NOT NULL,
    "canCreateAnnouncement" boolean CONSTRAINT club_members_can_create_announcement_not_null NOT NULL,
    "canManageMembers" boolean CONSTRAINT club_members_can_manage_members_not_null NOT NULL,
    status text NOT NULL,
    "addedByService" text,
    "joinedAt" timestamp without time zone CONSTRAINT club_members_joined_at_not_null NOT NULL
);


--
-- Name: club_members_club_member_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.club_members_club_member_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: club_members_club_member_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.club_members_club_member_id_seq OWNED BY public.club_members."clubMemberId";


--
-- Name: clubs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clubs (
    "clubId" integer CONSTRAINT clubs_club_id_not_null NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    description text,
    "logoUrl" text,
    status text NOT NULL,
    "createdByService" text,
    "isActive" boolean CONSTRAINT clubs_is_active_not_null NOT NULL,
    "createdAt" timestamp without time zone CONSTRAINT clubs_created_at_not_null NOT NULL,
    "updatedAt" timestamp without time zone CONSTRAINT clubs_updated_at_not_null NOT NULL
);


--
-- Name: clubs_club_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.clubs_club_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: clubs_club_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.clubs_club_id_seq OWNED BY public.clubs."clubId";


--
-- Name: comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comments (
    "commentId" integer CONSTRAINT comments_comment_id_not_null NOT NULL,
    "postId" integer CONSTRAINT comments_post_id_not_null NOT NULL,
    "userId" integer CONSTRAINT comments_user_id_not_null NOT NULL,
    content text NOT NULL,
    "isDeleted" boolean CONSTRAINT comments_is_deleted_not_null NOT NULL,
    "createdAt" timestamp without time zone CONSTRAINT comments_created_at_not_null NOT NULL
);


--
-- Name: comments_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.comments_comment_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: comments_comment_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.comments_comment_id_seq OWNED BY public.comments."commentId";


--
-- Name: friendships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.friendships (
    "friendshipId" integer CONSTRAINT friendships_friendship_id_not_null NOT NULL,
    "requesterId" integer CONSTRAINT friendships_requester_id_not_null NOT NULL,
    "receiverId" integer CONSTRAINT friendships_receiver_id_not_null NOT NULL,
    status text NOT NULL,
    "createdAt" timestamp without time zone CONSTRAINT friendships_created_at_not_null NOT NULL,
    "updatedAt" timestamp without time zone CONSTRAINT friendships_updated_at_not_null NOT NULL
);


--
-- Name: friendships_friendship_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.friendships_friendship_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: friendships_friendship_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.friendships_friendship_id_seq OWNED BY public.friendships."friendshipId";


--
-- Name: games; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.games (
    "gameId" integer CONSTRAINT games_game_id_not_null NOT NULL,
    name text NOT NULL,
    description text,
    "startDate" timestamp without time zone,
    "endDate" timestamp without time zone,
    "isActive" boolean CONSTRAINT games_is_active_not_null NOT NULL,
    "createdAt" timestamp without time zone CONSTRAINT games_created_at_not_null NOT NULL
);


--
-- Name: games_game_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.games_game_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: games_game_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.games_game_id_seq OWNED BY public.games."gameId";


--
-- Name: marketplace_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.marketplace_items (
    "itemId" integer CONSTRAINT marketplace_items_item_id_not_null NOT NULL,
    "sellerId" integer CONSTRAINT marketplace_items_seller_id_not_null NOT NULL,
    title text NOT NULL,
    description text,
    category text,
    price numeric(12,2),
    "imageUrl" text,
    status text NOT NULL,
    "createdAt" timestamp without time zone CONSTRAINT marketplace_items_created_at_not_null NOT NULL,
    "updatedAt" timestamp without time zone CONSTRAINT marketplace_items_updated_at_not_null NOT NULL
);


--
-- Name: marketplace_items_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.marketplace_items_item_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: marketplace_items_item_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.marketplace_items_item_id_seq OWNED BY public.marketplace_items."itemId";


--
-- Name: marketplace_reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.marketplace_reviews (
    "reviewId" integer NOT NULL,
    "tradeId" integer NOT NULL,
    "reviewerId" integer NOT NULL,
    "revieweeId" integer NOT NULL,
    rating integer NOT NULL,
    comment text,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_marketplace_reviews_distinct_users CHECK (("reviewerId" <> "revieweeId")),
    CONSTRAINT ck_marketplace_reviews_rating CHECK (((rating >= 1) AND (rating <= 5)))
);


--
-- Name: marketplace_reviews_reviewId_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."marketplace_reviews_reviewId_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: marketplace_reviews_reviewId_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."marketplace_reviews_reviewId_seq" OWNED BY public.marketplace_reviews."reviewId";


--
-- Name: marketplace_trades; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.marketplace_trades (
    "tradeId" integer NOT NULL,
    "itemId" integer NOT NULL,
    "sellerId" integer NOT NULL,
    "buyerId" integer NOT NULL,
    status character varying(16) DEFAULT 'pending'::character varying NOT NULL,
    "completedAt" timestamp with time zone,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_marketplace_trades_distinct_users CHECK (("sellerId" <> "buyerId")),
    CONSTRAINT ck_marketplace_trades_status CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'completed'::character varying, 'cancelled'::character varying])::text[])))
);


--
-- Name: marketplace_trades_tradeId_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."marketplace_trades_tradeId_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: marketplace_trades_tradeId_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."marketplace_trades_tradeId_seq" OWNED BY public.marketplace_trades."tradeId";


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    "notificationId" integer CONSTRAINT notifications_notification_id_not_null NOT NULL,
    "userId" integer CONSTRAINT notifications_user_id_not_null NOT NULL,
    "actorId" integer CONSTRAINT notifications_actor_id_not_null NOT NULL,
    type text NOT NULL,
    "targetType" text CONSTRAINT notifications_target_type_not_null NOT NULL,
    "targetId" text CONSTRAINT notifications_target_id_not_null NOT NULL,
    message text NOT NULL,
    "isRead" boolean CONSTRAINT notifications_is_read_not_null NOT NULL,
    "createdAt" timestamp without time zone CONSTRAINT notifications_created_at_not_null NOT NULL
);


--
-- Name: notifications_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.notifications_notification_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: notifications_notification_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.notifications_notification_id_seq OWNED BY public.notifications."notificationId";


--
-- Name: post_bookmarks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_bookmarks (
    "postId" integer NOT NULL,
    "userId" integer NOT NULL,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: post_likes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_likes (
    "postId" integer CONSTRAINT post_likes_post_id_not_null NOT NULL,
    "userId" integer CONSTRAINT post_likes_user_id_not_null NOT NULL,
    "createdAt" timestamp without time zone CONSTRAINT post_likes_created_at_not_null NOT NULL
);


--
-- Name: post_media; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_media (
    "mediaId" integer CONSTRAINT post_media_media_id_not_null NOT NULL,
    "postId" integer CONSTRAINT post_media_post_id_not_null NOT NULL,
    "mediaUrl" text CONSTRAINT post_media_media_url_not_null NOT NULL,
    "mediaType" text CONSTRAINT post_media_media_type_not_null NOT NULL,
    "sortOrder" integer CONSTRAINT post_media_sort_order_not_null NOT NULL
);


--
-- Name: post_media_media_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.post_media_media_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: post_media_media_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.post_media_media_id_seq OWNED BY public.post_media."mediaId";


--
-- Name: posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.posts (
    "postId" integer CONSTRAINT posts_post_id_not_null NOT NULL,
    "authorId" integer CONSTRAINT posts_author_id_not_null NOT NULL,
    "clubId" integer,
    "postType" text CONSTRAINT posts_post_type_not_null NOT NULL,
    content text,
    "mediaUrl" text,
    "mediaType" text,
    "originalPostId" integer,
    visibility text NOT NULL,
    "eventTitle" text,
    "eventStartTime" timestamp without time zone,
    "eventEndTime" timestamp without time zone,
    "eventLocation" text,
    "registrationLink" text,
    "likeCount" integer CONSTRAINT posts_like_count_not_null NOT NULL,
    "commentCount" integer CONSTRAINT posts_comment_count_not_null NOT NULL,
    "shareCount" integer CONSTRAINT posts_share_count_not_null NOT NULL,
    "bookmarkCount" integer CONSTRAINT posts_bookmark_count_not_null NOT NULL,
    "repostCount" integer CONSTRAINT posts_repost_count_not_null NOT NULL,
    "reportCount" integer CONSTRAINT posts_report_count_not_null NOT NULL,
    "engagementScore" double precision CONSTRAINT posts_engagement_score_not_null NOT NULL,
    "isDeleted" boolean CONSTRAINT posts_is_deleted_not_null NOT NULL,
    "createdAt" timestamp without time zone CONSTRAINT posts_created_at_not_null NOT NULL,
    "updatedAt" timestamp without time zone CONSTRAINT posts_updated_at_not_null NOT NULL
);


--
-- Name: posts_post_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.posts_post_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: posts_post_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.posts_post_id_seq OWNED BY public.posts."postId";


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version character varying(120) NOT NULL,
    "appliedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: signal_bar_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.signal_bar_items (
    "signalBarItemId" integer NOT NULL,
    title character varying(160) NOT NULL,
    link character varying(2048) NOT NULL,
    "position" integer NOT NULL,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: signal_bar_items_signalBarItemId_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."signal_bar_items_signalBarItemId_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: signal_bar_items_signalBarItemId_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."signal_bar_items_signalBarItemId_seq" OWNED BY public.signal_bar_items."signalBarItemId";


--
-- Name: user_badges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_badges (
    "userId" integer NOT NULL,
    "badgeId" character varying(80) NOT NULL,
    "earnedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: user_interests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_interests (
    "userId" integer NOT NULL,
    interest character varying(80) NOT NULL,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: user_points; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_points (
    "pointId" integer CONSTRAINT user_points_point_id_not_null NOT NULL,
    "userId" integer CONSTRAINT user_points_user_id_not_null NOT NULL,
    "gameId" integer,
    points integer NOT NULL,
    reason text,
    "createdAt" timestamp without time zone CONSTRAINT user_points_created_at_not_null NOT NULL
);


--
-- Name: user_points_point_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_points_point_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_points_point_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.user_points_point_id_seq OWNED BY public.user_points."pointId";


--
-- Name: user_preferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_preferences (
    "userId" integer NOT NULL,
    "notifyOfficial" boolean DEFAULT true NOT NULL,
    "notifyDepartment" boolean DEFAULT true NOT NULL,
    "notifyClub" boolean DEFAULT true NOT NULL,
    "notifyStudent" boolean DEFAULT false NOT NULL,
    "notifyExternal" boolean DEFAULT false NOT NULL,
    "profileVisibility" character varying(16) DEFAULT 'campus'::character varying NOT NULL,
    "eventHistoryVisibility" character varying(16) DEFAULT 'friends'::character varying NOT NULL,
    "marketplaceActivityVisibility" character varying(16) DEFAULT 'campus'::character varying NOT NULL,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_user_preferences_event_visibility CHECK ((("eventHistoryVisibility")::text = ANY ((ARRAY['private'::character varying, 'friends'::character varying, 'campus'::character varying])::text[]))),
    CONSTRAINT ck_user_preferences_marketplace_visibility CHECK ((("marketplaceActivityVisibility")::text = ANY ((ARRAY['private'::character varying, 'friends'::character varying, 'campus'::character varying])::text[]))),
    CONSTRAINT ck_user_preferences_profile_visibility CHECK ((("profileVisibility")::text = ANY ((ARRAY['private'::character varying, 'friends'::character varying, 'campus'::character varying])::text[])))
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    "userId" integer CONSTRAINT users_user_id_not_null NOT NULL,
    "fullName" text CONSTRAINT users_full_name_not_null NOT NULL,
    username text NOT NULL,
    email text NOT NULL,
    "passwordHash" text CONSTRAINT users_password_hash_not_null NOT NULL,
    "accountRole" text CONSTRAINT users_account_role_not_null NOT NULL,
    "dateOfBirth" date,
    department text,
    semester integer,
    "batchYear" integer,
    bio text,
    "profilePhotoUrl" text,
    "profileVisibility" text CONSTRAINT users_profile_visibility_not_null NOT NULL,
    "notificationsEnabled" boolean CONSTRAINT users_notifications_enabled_not_null NOT NULL,
    "reputationScore" double precision CONSTRAINT users_reputation_score_not_null NOT NULL,
    "safetyScore" double precision CONSTRAINT users_safety_score_not_null NOT NULL,
    "isActive" boolean CONSTRAINT users_is_active_not_null NOT NULL,
    "createdAt" timestamp without time zone CONSTRAINT users_created_at_not_null NOT NULL,
    "updatedAt" timestamp without time zone CONSTRAINT users_updated_at_not_null NOT NULL,
    "lastActiveAt" timestamp with time zone,
    CONSTRAINT ck_users_department CHECK (((department IS NULL) OR (department = ANY (ARRAY['CS'::text, 'Mech'::text, 'ECE'::text, 'Electrical'::text, 'AIML'::text, 'Information Science'::text]))))
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_user_id_seq OWNED BY public.users."userId";


--
-- Name: chat_messages messageId; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages ALTER COLUMN "messageId" SET DEFAULT nextval('public.chat_messages_message_id_seq'::regclass);


--
-- Name: chat_threads threadId; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_threads ALTER COLUMN "threadId" SET DEFAULT nextval('public.chat_threads_thread_id_seq'::regclass);


--
-- Name: club_members clubMemberId; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.club_members ALTER COLUMN "clubMemberId" SET DEFAULT nextval('public.club_members_club_member_id_seq'::regclass);


--
-- Name: clubs clubId; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clubs ALTER COLUMN "clubId" SET DEFAULT nextval('public.clubs_club_id_seq'::regclass);


--
-- Name: comments commentId; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments ALTER COLUMN "commentId" SET DEFAULT nextval('public.comments_comment_id_seq'::regclass);


--
-- Name: friendships friendshipId; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friendships ALTER COLUMN "friendshipId" SET DEFAULT nextval('public.friendships_friendship_id_seq'::regclass);


--
-- Name: games gameId; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.games ALTER COLUMN "gameId" SET DEFAULT nextval('public.games_game_id_seq'::regclass);


--
-- Name: marketplace_items itemId; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marketplace_items ALTER COLUMN "itemId" SET DEFAULT nextval('public.marketplace_items_item_id_seq'::regclass);


--
-- Name: marketplace_reviews reviewId; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marketplace_reviews ALTER COLUMN "reviewId" SET DEFAULT nextval('public."marketplace_reviews_reviewId_seq"'::regclass);


--
-- Name: marketplace_trades tradeId; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marketplace_trades ALTER COLUMN "tradeId" SET DEFAULT nextval('public."marketplace_trades_tradeId_seq"'::regclass);


--
-- Name: notifications notificationId; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications ALTER COLUMN "notificationId" SET DEFAULT nextval('public.notifications_notification_id_seq'::regclass);


--
-- Name: post_media mediaId; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_media ALTER COLUMN "mediaId" SET DEFAULT nextval('public.post_media_media_id_seq'::regclass);


--
-- Name: posts postId; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts ALTER COLUMN "postId" SET DEFAULT nextval('public.posts_post_id_seq'::regclass);


--
-- Name: signal_bar_items signalBarItemId; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signal_bar_items ALTER COLUMN "signalBarItemId" SET DEFAULT nextval('public."signal_bar_items_signalBarItemId_seq"'::regclass);


--
-- Name: user_points pointId; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_points ALTER COLUMN "pointId" SET DEFAULT nextval('public.user_points_point_id_seq'::regclass);


--
-- Name: users userId; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users ALTER COLUMN "userId" SET DEFAULT nextval('public.users_user_id_seq'::regclass);


--
-- Name: badges badges_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.badges
    ADD CONSTRAINT badges_pkey PRIMARY KEY ("badgeId");


--
-- Name: campus_events campus_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campus_events
    ADD CONSTRAINT campus_events_pkey PRIMARY KEY ("eventId");


--
-- Name: chat_messages chat_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY ("messageId");


--
-- Name: chat_participants chat_participants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_participants
    ADD CONSTRAINT chat_participants_pkey PRIMARY KEY ("threadId", "userId");


--
-- Name: chat_threads chat_threads_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_threads
    ADD CONSTRAINT chat_threads_pkey PRIMARY KEY ("threadId");


--
-- Name: club_followers club_followers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.club_followers
    ADD CONSTRAINT club_followers_pkey PRIMARY KEY ("clubId", "userId");


--
-- Name: club_members club_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.club_members
    ADD CONSTRAINT club_members_pkey PRIMARY KEY ("clubMemberId");


--
-- Name: clubs clubs_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clubs
    ADD CONSTRAINT clubs_name_key UNIQUE (name);


--
-- Name: clubs clubs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clubs
    ADD CONSTRAINT clubs_pkey PRIMARY KEY ("clubId");


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY ("commentId");


--
-- Name: friendships friendships_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friendships
    ADD CONSTRAINT friendships_pkey PRIMARY KEY ("friendshipId");


--
-- Name: games games_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_pkey PRIMARY KEY ("gameId");


--
-- Name: marketplace_items marketplace_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marketplace_items
    ADD CONSTRAINT marketplace_items_pkey PRIMARY KEY ("itemId");


--
-- Name: marketplace_reviews marketplace_reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marketplace_reviews
    ADD CONSTRAINT marketplace_reviews_pkey PRIMARY KEY ("reviewId");


--
-- Name: marketplace_trades marketplace_trades_itemId_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marketplace_trades
    ADD CONSTRAINT "marketplace_trades_itemId_key" UNIQUE ("itemId");


--
-- Name: marketplace_trades marketplace_trades_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marketplace_trades
    ADD CONSTRAINT marketplace_trades_pkey PRIMARY KEY ("tradeId");


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY ("notificationId");


--
-- Name: post_bookmarks post_bookmarks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_bookmarks
    ADD CONSTRAINT post_bookmarks_pkey PRIMARY KEY ("postId", "userId");


--
-- Name: post_likes post_likes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_likes
    ADD CONSTRAINT post_likes_pkey PRIMARY KEY ("postId", "userId");


--
-- Name: post_media post_media_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_media
    ADD CONSTRAINT post_media_pkey PRIMARY KEY ("mediaId");


--
-- Name: posts posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY ("postId");


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: signal_bar_items signal_bar_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signal_bar_items
    ADD CONSTRAINT signal_bar_items_pkey PRIMARY KEY ("signalBarItemId");


--
-- Name: club_members uq_club_members_club_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.club_members
    ADD CONSTRAINT uq_club_members_club_user UNIQUE ("clubId", "userId");


--
-- Name: friendships uq_friendships_requester_receiver; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friendships
    ADD CONSTRAINT uq_friendships_requester_receiver UNIQUE ("requesterId", "receiverId");


--
-- Name: marketplace_reviews uq_marketplace_reviews_trade_reviewer; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marketplace_reviews
    ADD CONSTRAINT uq_marketplace_reviews_trade_reviewer UNIQUE ("tradeId", "reviewerId");


--
-- Name: signal_bar_items uq_signal_bar_items_position; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signal_bar_items
    ADD CONSTRAINT uq_signal_bar_items_position UNIQUE ("position");


--
-- Name: user_badges user_badges_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_badges
    ADD CONSTRAINT user_badges_pkey PRIMARY KEY ("userId", "badgeId");


--
-- Name: user_interests user_interests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_interests
    ADD CONSTRAINT user_interests_pkey PRIMARY KEY ("userId", interest);


--
-- Name: user_points user_points_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_points
    ADD CONSTRAINT user_points_pkey PRIMARY KEY ("pointId");


--
-- Name: user_preferences user_preferences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT user_preferences_pkey PRIMARY KEY ("userId");


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY ("userId");


--
-- Name: ix_campus_events_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_campus_events_date ON public.campus_events USING btree ("eventDate", "eventId");


--
-- Name: ix_chat_messages_thread_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_chat_messages_thread_id ON public.chat_messages USING btree ("threadId");


--
-- Name: ix_club_members_club_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_club_members_club_id ON public.club_members USING btree ("clubId");


--
-- Name: ix_club_members_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_club_members_user_id ON public.club_members USING btree ("userId");


--
-- Name: ix_clubs_slug; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ix_clubs_slug ON public.clubs USING btree (slug);


--
-- Name: ix_comments_post_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_comments_post_id ON public.comments USING btree ("postId");


--
-- Name: ix_comments_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_comments_user_id ON public.comments USING btree ("userId");


--
-- Name: ix_friendships_receiver_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_friendships_receiver_id ON public.friendships USING btree ("receiverId");


--
-- Name: ix_friendships_requester_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_friendships_requester_id ON public.friendships USING btree ("requesterId");


--
-- Name: ix_marketplace_items_seller_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_marketplace_items_seller_id ON public.marketplace_items USING btree ("sellerId");


--
-- Name: ix_marketplace_reviews_reviewee; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_marketplace_reviews_reviewee ON public.marketplace_reviews USING btree ("revieweeId", "tradeId");


--
-- Name: ix_marketplace_reviews_revieweeId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "ix_marketplace_reviews_revieweeId" ON public.marketplace_reviews USING btree ("revieweeId");


--
-- Name: ix_marketplace_reviews_tradeId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "ix_marketplace_reviews_tradeId" ON public.marketplace_reviews USING btree ("tradeId");


--
-- Name: ix_marketplace_trades_buyerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "ix_marketplace_trades_buyerId" ON public.marketplace_trades USING btree ("buyerId");


--
-- Name: ix_marketplace_trades_seller; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_marketplace_trades_seller ON public.marketplace_trades USING btree ("sellerId", status);


--
-- Name: ix_marketplace_trades_sellerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "ix_marketplace_trades_sellerId" ON public.marketplace_trades USING btree ("sellerId");


--
-- Name: ix_notifications_actor_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_notifications_actor_id ON public.notifications USING btree ("actorId");


--
-- Name: ix_notifications_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_notifications_type ON public.notifications USING btree (type);


--
-- Name: ix_notifications_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_notifications_user_id ON public.notifications USING btree ("userId");


--
-- Name: ix_post_bookmarks_user_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_post_bookmarks_user_created ON public.post_bookmarks USING btree ("userId", "createdAt" DESC, "postId" DESC);


--
-- Name: ix_post_media_post_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_post_media_post_id ON public.post_media USING btree ("postId");


--
-- Name: ix_posts_author_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_posts_author_id ON public.posts USING btree ("authorId");


--
-- Name: ix_posts_club_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_posts_club_id ON public.posts USING btree ("clubId");


--
-- Name: ix_signal_bar_items_position; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_signal_bar_items_position ON public.signal_bar_items USING btree ("position", "signalBarItemId");


--
-- Name: ix_user_points_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_user_points_user_id ON public.user_points USING btree ("userId");


--
-- Name: ix_users_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ix_users_email ON public.users USING btree (email);


--
-- Name: ix_users_username; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ix_users_username ON public.users USING btree (username);


--
-- Name: uq_chat_threads_direct_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_chat_threads_direct_key ON public.chat_threads USING btree ("directKey") WHERE ("directKey" IS NOT NULL);


--
-- Name: uq_marketplace_trades_item; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_marketplace_trades_item ON public.marketplace_trades USING btree ("itemId");


--
-- Name: club_followers club_followers_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.club_followers
    ADD CONSTRAINT club_followers_user_id_fkey FOREIGN KEY ("userId") REFERENCES public.users("userId");


--
-- Name: club_members club_members_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.club_members
    ADD CONSTRAINT club_members_user_id_fkey FOREIGN KEY ("userId") REFERENCES public.users("userId");


--
-- Name: comments comments_post_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_post_id_fkey FOREIGN KEY ("postId") REFERENCES public.posts("postId");


--
-- Name: comments comments_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_user_id_fkey FOREIGN KEY ("userId") REFERENCES public.users("userId");


--
-- Name: chat_messages fk_chat_messages_sender; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fk_chat_messages_sender FOREIGN KEY ("senderId") REFERENCES public.users("userId") ON DELETE CASCADE;


--
-- Name: chat_messages fk_chat_messages_thread; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fk_chat_messages_thread FOREIGN KEY ("threadId") REFERENCES public.chat_threads("threadId") ON DELETE CASCADE;


--
-- Name: chat_participants fk_chat_participants_thread; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_participants
    ADD CONSTRAINT fk_chat_participants_thread FOREIGN KEY ("threadId") REFERENCES public.chat_threads("threadId") ON DELETE CASCADE;


--
-- Name: chat_participants fk_chat_participants_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_participants
    ADD CONSTRAINT fk_chat_participants_user FOREIGN KEY ("userId") REFERENCES public.users("userId") ON DELETE CASCADE;


--
-- Name: chat_threads fk_chat_threads_club; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_threads
    ADD CONSTRAINT fk_chat_threads_club FOREIGN KEY ("clubId") REFERENCES public.clubs("clubId") ON DELETE SET NULL;


--
-- Name: chat_threads fk_chat_threads_marketplace_item; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_threads
    ADD CONSTRAINT fk_chat_threads_marketplace_item FOREIGN KEY ("marketplaceItemId") REFERENCES public.marketplace_items("itemId") ON DELETE SET NULL;


--
-- Name: club_followers fk_club_followers_club; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.club_followers
    ADD CONSTRAINT fk_club_followers_club FOREIGN KEY ("clubId") REFERENCES public.clubs("clubId") ON DELETE CASCADE;


--
-- Name: club_members fk_club_members_club; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.club_members
    ADD CONSTRAINT fk_club_members_club FOREIGN KEY ("clubId") REFERENCES public.clubs("clubId") ON DELETE CASCADE;


--
-- Name: marketplace_reviews fk_marketplace_reviews_reviewee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marketplace_reviews
    ADD CONSTRAINT fk_marketplace_reviews_reviewee FOREIGN KEY ("revieweeId") REFERENCES public.users("userId") ON DELETE CASCADE;


--
-- Name: marketplace_reviews fk_marketplace_reviews_reviewer; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marketplace_reviews
    ADD CONSTRAINT fk_marketplace_reviews_reviewer FOREIGN KEY ("reviewerId") REFERENCES public.users("userId") ON DELETE CASCADE;


--
-- Name: marketplace_reviews fk_marketplace_reviews_trade; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marketplace_reviews
    ADD CONSTRAINT fk_marketplace_reviews_trade FOREIGN KEY ("tradeId") REFERENCES public.marketplace_trades("tradeId") ON DELETE CASCADE;


--
-- Name: marketplace_trades fk_marketplace_trades_buyer; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marketplace_trades
    ADD CONSTRAINT fk_marketplace_trades_buyer FOREIGN KEY ("buyerId") REFERENCES public.users("userId") ON DELETE CASCADE;


--
-- Name: marketplace_trades fk_marketplace_trades_item; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marketplace_trades
    ADD CONSTRAINT fk_marketplace_trades_item FOREIGN KEY ("itemId") REFERENCES public.marketplace_items("itemId") ON DELETE CASCADE;


--
-- Name: marketplace_trades fk_marketplace_trades_seller; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marketplace_trades
    ADD CONSTRAINT fk_marketplace_trades_seller FOREIGN KEY ("sellerId") REFERENCES public.users("userId") ON DELETE CASCADE;


--
-- Name: posts fk_posts_club; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT fk_posts_club FOREIGN KEY ("clubId") REFERENCES public.clubs("clubId") ON DELETE SET NULL;


--
-- Name: user_badges fk_user_badges_badge; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_badges
    ADD CONSTRAINT fk_user_badges_badge FOREIGN KEY ("badgeId") REFERENCES public.badges("badgeId") ON DELETE CASCADE;


--
-- Name: user_badges fk_user_badges_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_badges
    ADD CONSTRAINT fk_user_badges_user FOREIGN KEY ("userId") REFERENCES public.users("userId") ON DELETE CASCADE;


--
-- Name: user_interests fk_user_interests_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_interests
    ADD CONSTRAINT fk_user_interests_user FOREIGN KEY ("userId") REFERENCES public.users("userId") ON DELETE CASCADE;


--
-- Name: user_preferences fk_user_preferences_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT fk_user_preferences_user FOREIGN KEY ("userId") REFERENCES public.users("userId") ON DELETE CASCADE;


--
-- Name: friendships friendships_receiver_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friendships
    ADD CONSTRAINT friendships_receiver_id_fkey FOREIGN KEY ("receiverId") REFERENCES public.users("userId");


--
-- Name: friendships friendships_requester_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friendships
    ADD CONSTRAINT friendships_requester_id_fkey FOREIGN KEY ("requesterId") REFERENCES public.users("userId");


--
-- Name: marketplace_items marketplace_items_seller_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marketplace_items
    ADD CONSTRAINT marketplace_items_seller_id_fkey FOREIGN KEY ("sellerId") REFERENCES public.users("userId");


--
-- Name: notifications notifications_actor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_actor_id_fkey FOREIGN KEY ("actorId") REFERENCES public.users("userId");


--
-- Name: notifications notifications_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY ("userId") REFERENCES public.users("userId");


--
-- Name: post_bookmarks post_bookmarks_postId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_bookmarks
    ADD CONSTRAINT "post_bookmarks_postId_fkey" FOREIGN KEY ("postId") REFERENCES public.posts("postId") ON DELETE CASCADE;


--
-- Name: post_bookmarks post_bookmarks_userId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_bookmarks
    ADD CONSTRAINT "post_bookmarks_userId_fkey" FOREIGN KEY ("userId") REFERENCES public.users("userId") ON DELETE CASCADE;


--
-- Name: post_likes post_likes_post_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_likes
    ADD CONSTRAINT post_likes_post_id_fkey FOREIGN KEY ("postId") REFERENCES public.posts("postId");


--
-- Name: post_likes post_likes_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_likes
    ADD CONSTRAINT post_likes_user_id_fkey FOREIGN KEY ("userId") REFERENCES public.users("userId");


--
-- Name: post_media post_media_post_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_media
    ADD CONSTRAINT post_media_post_id_fkey FOREIGN KEY ("postId") REFERENCES public.posts("postId") ON DELETE CASCADE;


--
-- Name: posts posts_author_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_author_id_fkey FOREIGN KEY ("authorId") REFERENCES public.users("userId");


--
-- Name: posts posts_original_post_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_original_post_id_fkey FOREIGN KEY ("originalPostId") REFERENCES public.posts("postId");


--
-- Name: user_points user_points_game_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_points
    ADD CONSTRAINT user_points_game_id_fkey FOREIGN KEY ("gameId") REFERENCES public.games("gameId");


--
-- Name: user_points user_points_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_points
    ADD CONSTRAINT user_points_user_id_fkey FOREIGN KEY ("userId") REFERENCES public.users("userId");


--
-- PostgreSQL database dump complete
--

-- A fresh database starts at the consolidated schema baseline.
INSERT INTO public.schema_migrations (version, "appliedAt")
VALUES ('004_department_options', CURRENT_TIMESTAMP);

COMMIT;
