/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#f8f9fb",
        "surface-dim": "#d6d9de",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f1f8",
        "surface-container": "#e9e7f3",
        "surface-container-high": "#dfdced",
        "surface-container-highest": "#d2cfe3",
        "on-surface": "#111317",
        "on-surface-variant": "#4a4f57",
        "inverse-surface": "#171b22",
        "inverse-on-surface": "#f3f4f6",
        outline: "#777d86",
        "outline-variant": "#c8ccd3",
        "surface-tint": "#221D5C",
        primary: "#221D5C",
        "on-primary": "#ffffff",
        "primary-container": "#312978",
        "on-primary-container": "#ffffff",
        "inverse-primary": "#a79fe0",
        secondary: "#EC2024",
        "on-secondary": "#ffffff",
        "secondary-container": "#f45c5f",
        "on-secondary-container": "#ffffff",
        tertiary: "#191c22",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#2b313a",
        "on-tertiary-container": "#ffffff",
        "error-container": "#ffdad6",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "primary-fixed": "#ddd9f4",
        "primary-fixed-dim": "#b3abd9",
        "on-primary-fixed": "#15103e",
        "on-primary-fixed-variant": "#312978",
        "secondary-fixed": "#ffd7d7",
        "secondary-fixed-dim": "#ff9a9c",
        "on-secondary-fixed": "#4d0506",
        "on-secondary-fixed-variant": "#b6171b",
        "tertiary-fixed": "#d4d7dc",
        "tertiary-fixed-dim": "#a8afb9",
        "on-tertiary-fixed": "#0f1115",
        "on-tertiary-fixed-variant": "#2b313a",
        background: "#f7f6fb",
        "on-background": "#111317",
        "surface-variant": "#e1e4e9",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        xs: "4px",
        sm: "12px",
        md: "24px",
        lg: "40px",
        xl: "64px",
        gutter: "16px",
        "container-margin": "20px",
        "container-max": "1280px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        unit: "8px",
      },
      fontFamily: {
        "headline-md": ["Space Grotesk", "sans-serif"],
        "display-lg": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "2.875rem",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": ["1.925rem", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["1.45rem", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["1.075rem", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["0.95rem", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["0.825rem", { lineHeight: "1.4", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};

module.exports = config;
