from __future__ import annotations

import os
import re
import unittest
import uuid
from pathlib import Path

import psycopg


TEST_DATABASE_URL = os.getenv("TEST_POSTGRES_DATABASE_URL", "")
MIGRATION_PATH = Path(__file__).resolve().parents[1] / "migrations" / "001_frontend_api_requirements.postgresql"


def psycopg_url(value: str) -> str:
    return value.replace("postgresql+psycopg://", "postgresql://", 1)


class PostgreSqlMigrationFileTest(unittest.TestCase):
    def test_migration_contains_partial_schema_repairs_and_version_marker(self) -> None:
        migration_sql = MIGRATION_PATH.read_text(encoding="utf-8")
        self.assertIn('ADD COLUMN IF NOT EXISTS "lastActiveAt" TIMESTAMPTZ', migration_sql)
        self.assertIn('ADD COLUMN IF NOT EXISTS "directKey" VARCHAR(64)', migration_sql)
        self.assertIn("timestamp without time zone", migration_sql)
        self.assertIn("current_setting(''TimeZone'')", migration_sql)
        self.assertIn("ON DELETE CASCADE", migration_sql)
        self.assertIn("001_frontend_api_requirements", migration_sql)
        self.assertFalse(re.search(r"\bDROP\s+TABLE\b", migration_sql, flags=re.IGNORECASE))


@unittest.skipUnless(TEST_DATABASE_URL, "TEST_POSTGRES_DATABASE_URL is not configured")
class PostgreSqlMigrationTest(unittest.TestCase):
    def test_repairs_a_partially_created_schema_and_is_idempotent(self) -> None:
        schema_name = f"campus_nexus_migration_{uuid.uuid4().hex}"
        self.assertRegex(schema_name, r"^[a-z0-9_]+$")
        connection = psycopg.connect(psycopg_url(TEST_DATABASE_URL), autocommit=True)
        try:
            with connection.cursor() as cursor:
                cursor.execute(f'CREATE SCHEMA "{schema_name}"')
                cursor.execute(f'SET search_path TO "{schema_name}"')
                cursor.execute(
                    """
                    CREATE TABLE users (
                        "userId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
                    );
                    CREATE TABLE clubs (
                        "clubId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
                    );
                    CREATE TABLE marketplace_items (
                        "itemId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
                    );
                    CREATE TABLE chat_threads (
                        "threadId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "threadType" TEXT NOT NULL DEFAULT 'direct',
                        "clubId" INTEGER REFERENCES clubs("clubId"),
                        "marketplaceItemId" INTEGER REFERENCES marketplace_items("itemId"),
                        "createdAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                    );
                    CREATE TABLE chat_participants (
                        "threadId" INTEGER NOT NULL REFERENCES chat_threads("threadId"),
                        "userId" INTEGER NOT NULL REFERENCES users("userId"),
                        "joinedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        "lastReadAt" TIMESTAMP WITHOUT TIME ZONE,
                        PRIMARY KEY ("threadId", "userId")
                    );
                    CREATE TABLE chat_messages (
                        "messageId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "threadId" INTEGER NOT NULL REFERENCES chat_threads("threadId"),
                        "senderId" INTEGER NOT NULL REFERENCES users("userId"),
                        content TEXT,
                        "isDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
                        "createdAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                    );
                    CREATE TABLE user_preferences (
                        "userId" INTEGER PRIMARY KEY REFERENCES users("userId"),
                        "notifyOfficial" BOOLEAN NOT NULL,
                        "notifyDepartment" BOOLEAN NOT NULL,
                        "notifyClub" BOOLEAN NOT NULL,
                        "notifyStudent" BOOLEAN NOT NULL,
                        "notifyExternal" BOOLEAN NOT NULL,
                        "profileVisibility" VARCHAR(16) NOT NULL,
                        "eventHistoryVisibility" VARCHAR(16) NOT NULL,
                        "marketplaceActivityVisibility" VARCHAR(16) NOT NULL,
                        "createdAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                        "updatedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                        CONSTRAINT ck_user_preferences_profile_visibility
                            CHECK ("profileVisibility" IN ('private', 'friends', 'campus')),
                        CONSTRAINT ck_user_preferences_event_visibility
                            CHECK ("eventHistoryVisibility" IN ('private', 'friends', 'campus')),
                        CONSTRAINT ck_user_preferences_marketplace_visibility
                            CHECK ("marketplaceActivityVisibility" IN ('private', 'friends', 'campus'))
                    );
                    """,
                    prepare=False,
                )

                migration_sql = MIGRATION_PATH.read_text(encoding="utf-8")
                self.assertFalse(re.search(r"\bDROP\s+TABLE\b", migration_sql, flags=re.IGNORECASE))
                cursor.execute(migration_sql, prepare=False)
                cursor.execute(migration_sql, prepare=False)

                cursor.execute(
                    """
                    SELECT data_type
                    FROM information_schema.columns
                    WHERE table_schema = current_schema()
                      AND table_name = 'user_preferences'
                      AND column_name = 'createdAt'
                    """
                )
                self.assertEqual(cursor.fetchone()[0], "timestamp with time zone")

                cursor.execute(
                    """
                    SELECT column_default
                    FROM information_schema.columns
                    WHERE table_schema = current_schema()
                      AND table_name = 'user_preferences'
                      AND column_name = 'notifyOfficial'
                    """
                )
                self.assertEqual(cursor.fetchone()[0], "true")

                cursor.execute(
                    """
                    SELECT delete_rule
                    FROM information_schema.referential_constraints
                    WHERE constraint_schema = current_schema()
                      AND constraint_name = 'fk_chat_participants_thread'
                    """
                )
                self.assertEqual(cursor.fetchone()[0], "CASCADE")

                cursor.execute(
                    """
                    SELECT COUNT(*)
                    FROM schema_migrations
                    WHERE version = '001_frontend_api_requirements'
                    """
                )
                self.assertEqual(cursor.fetchone()[0], 1)

                for table_name, column_name in (
                    ("users", "lastActiveAt"),
                    ("chat_threads", "directKey"),
                ):
                    cursor.execute(
                        """
                        SELECT COUNT(*)
                        FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = %s
                          AND column_name = %s
                        """,
                        (table_name, column_name),
                    )
                    self.assertEqual(cursor.fetchone()[0], 1)
        finally:
            connection.rollback()
            with connection.cursor() as cursor:
                cursor.execute("SET search_path TO public")
                cursor.execute(f'DROP SCHEMA IF EXISTS "{schema_name}" CASCADE')
            connection.close()


if __name__ == "__main__":
    unittest.main()
